update several deps
tikv/tikv pull request #12775
Opened 2022-06-07 04:50 UTC by BusyJay

### What is changed and how it works?

Issue Number: Close #12773.

What's Changed:

```commit-message
replace signal with signal-hook and update other deps by depbot.
```

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

```release-note
None
```

2022-06-07 05:50 UTC, sticnarf approved these changes
LGTM

2022-06-07 05:52 UTC, sticnarf requested changes
Oops, tidb_query needs to be fixed to adapt ordered_float changes

2022-06-08 03:30 UTC, sticnarf approved these changes

2022-06-08 21:32 UTC, BusyJay commented on components/external_storage/export/src/bin/tikv-cloud-storage.rs
> +        let mut signals = Signals::new(&[SIGTERM, SIGINT, SIGHUP]).unwrap();
They should not be used at all.

2022-06-10 14:30 UTC, zhangjinpeng1987 approved these changes
LGTM

2022-06-10 14:30 UTC, zhangjinpeng1987 commented
/merge

2022-06-10 14:48 UTC, merged