In-memory engine: fix gc may filter keys of onging snapshot
tikv/tikv pull request #17288
Opened 2024-07-22 04:46 UTC by SpadeA-Tang

### What is changed and how it works?

Issue Number: Close https://github.com/tikv/tikv/issues/17282

What's Changed:

```commit-message
fix gc may filter keys of onging snapshot
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None
```

2024-07-22 09:50 UTC, glorv approved these changes
LGTM

2024-07-22 09:50 UTC, glorv commented on components/range_cache_memory_engine/src/background.rs
> +                        )
```suggestion
                        m.range_snapshot_list()
                            .min_snapshot_ts()
```

2024-07-22 10:13 UTC, overvenus approved these changes

2024-07-22 10:20 UTC, overvenus requested changes
(Prevent merge)

2024-07-22 10:20 UTC, overvenus commented on Cargo.lock
> -version = "111.25.0+1.1.1t"
Any reason for changing openssl?

2024-07-23 02:56 UTC, LykxSassinator approved these changes
LGTM

2024-07-23 03:45 UTC, SpadeA-Tang commented on Cargo.lock
> -version = "111.25.0+1.1.1t"
reverted

2024-07-23 06:00 UTC, overvenus commented on Cargo.lock
> -version = "111.25.0+1.1.1t"
It has been fixed #17292

2024-07-23 06:01 UTC, overvenus approved these changes

2024-07-23 06:10 UTC, merged